export {
  generateDoubleElimination,
  generateSingleElimination,
  generateRoundRobin,
  generateSwiss,
  generateGroupsPlayoff,
  generateArmfight,
  getRoundRobinStandings,
  getSwissStandings,
  getGroupStandings,
  getFinalPlacements,
  selectWinner,
  propagateResults,
  findMatch,
  walkBracketMatches,
  isPlayableMatch,
  getPlayerObj,
  resetMatch,
  canRecordResult,
  validateResult,
  replacePlayerInSlot,
  withdrawPlayerFromSlot,
  // Armfight (sub-project B)
  recordLeg,
  forfeitBout,
  getBoutScore,
  isArmfightBoutResult,
} from './bracket-logic';
export type {
  Player,
  Match,
  GrandFinalMatch,
  SuperFinalMatch,
  BracketData,
  ValidationResult,
  Standing,
  FinalPlacement,
  GroupStage,
  // Armfight (sub-project B)
  ArmfightHand,
  LegWinType,
  ArmfightBoutStatus,
  ArmfightLeg,
  ArmfightBoutResult,
  ArmfightPairSpec,
  RecordLegOptions,
} from './types';
export type { BracketSection, BracketMatchVisitor } from './bracket-logic';
export { TBD_PLAYER, BYE_PLAYER } from './types';
